server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apitrail?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456