spring:
  profiles:
    active: docker
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      max-file-size: 200MB #设置上传文件大小不得超过200MB
      max-request-size: 200MB #设置一次请求的数据量不得超过200MB
      enabled: true
